server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      connect-string: :2181
      host: 192.168.31.207
      port: 8500
      discovery:
        service-name: ${spring.application.name}