server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            - After=2021-03-03T21:26:57.401+08:00[Asia/Shanghai]
#            - Before=2022-03-03T21:26:57.401+08:00[Asia/Shanghai]
#            - Between=2021-03-03T21:26:57.401+08:00[Asia/Shanghai],2022-03-03T21:26:57.401+08:00[Asia/Shanghai]
            - Cookie=username,zzyy
            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式   http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:1234"
            - Host=**.atguigu.com     #curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:1234" -H "Host:www.atguigu.com"
            - Method=GET  #curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:1234" -H "Host:www.atguigu.com" -X GET
            - Query=foo, ba*  #curl http://localhost:9527/payment/lb?foo=bar --cookie "username=zzyy" -H "X-Request-Id:1234" -H "Host:www.atguigu.com" -X GET   .代表一个占位  #匹配方式正则匹配

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka